# Generated by Django 4.2.8 on 2023-12-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='', max_length=256, upload_to=''),
        ),
    ]
