# Generated by Django 4.2.8 on 2023-12-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_profile',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo de profil'),
        ),
    ]
